services:
  - type: web
    name: watchcompany
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
